plugins:
  - name: solidity
  - name: vyper
  - name: hardhat
  - name: infura

# require OpenZepplin Contracts
dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.6.0

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.6.0"

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: hardhat