# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: hardhat-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.10
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"

reports:
  exclude_contracts:
    - SafeMath
